default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: aha_development

test:
  <<: *default
  database: aha_test

production:
  primary: &primary_production
    <<: *default
    database: mattsoh_aha_production
    host: /var/run/postgres

  cache:
    <<: *primary_production
    database: mattsoh_aha_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: mattsoh_aha_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: mattsoh_aha_production_cable
    migrations_paths: db/cable_migrate
